# Generated by Django 2.2.6 on 2019-10-08 19:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 8, 19, 42, 43, 383380, tzinfo=utc)),
        ),
    ]
