# Generated by Django 2.2.6 on 2019-10-17 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_app', '0002_auto_20191008_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_heading', models.CharField(max_length=250)),
                ('article_body', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='transfer',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
